#################################
# Image - example configuration #
#################################

# These are example definition of Image component.
# In order to use the component, you first must call Image::setConfig($pathToYourConfig).
Image:
    Library: gd
    Quality: 90
    # You can overwrite the default driver by providing your own.
    # How to create a new driver, read in the Readme.md file.
    # If you don't wish to change the default driver,
    # just ommit this definition in your config file.
    Bridge: \Webiny\Component\Image\Bridge\Imagine\Imagine
    # Entries under ClassLoader are automatically registered
    # with ClassLoader. You don't need this part if you are using Composer autoload.
    ClassLoader:
        Imagine: /var/Vendors/Imagine/lib/Imagine